sonar.projectKey=mi-proyecto-restaurante
sonar.projectName=Restaurante Backend
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts

# Language
sonar.language=ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=node_modules/**, dist/**, prisma/migrations/**, src/types/**, **/*.d.ts
sonar.coverage.exclusions=src/app.ts, src/setup.ts, src/config/**, src/docs/**, src/utils/errores.utils.ts, src/utils/respuestas.utils.ts

# Encoding
sonar.sourceEncoding=UTF-8
