export const ROLES = {
  ADMIN: 'ADMIN',
  MESERO: 'MESERO',
  COCINA: 'COCINA',
  CAJERO: 'CAJERO',
} as const;

export const PERMISOS = {
  USUARIOS_VER: 'USUARIOS_VER',
  USUARIOS_CREAR: 'USUARIOS_CREAR',
  USUARIOS_EDITAR: 'USUARIOS_EDITAR',
  USUARIOS_BORRAR: 'USUARIOS_BORRAR',
  PLATILLOS_VER: 'PLATILLOS_VER',
  PLATILLOS_CREAR: 'PLATILLOS_CREAR',
  PLATILLOS_EDITAR: 'PLATILLOS_EDITAR',
  PLATILLOS_BORRAR: 'PLATILLOS_BORRAR',
  ORDENES_VER: 'ORDENES_VER',
  ORDENES_CREAR: 'ORDENES_CREAR',
  ORDENES_ESTADO: 'ORDENES_ESTADO',
  ORDENES_CANCELAR: 'ORDENES_CANCELAR',
  CONFIG_VER: 'CONFIG_VER',
  AUDITORIA_VER: 'AUDITORIA_VER',
  REPORTES_VER: 'REPORTES_VER',
  CLIENTES_VER: 'CLIENTES_VER',
  CLIENTES_CREAR: 'CLIENTES_CREAR',
  CLIENTES_EDITAR: 'CLIENTES_EDITAR',
  CLIENTES_BORRAR: 'CLIENTES_BORRAR',
  RESERVACIONES_VER: 'RESERVACIONES_VER',
  RESERVACIONES_CREAR: 'RESERVACIONES_CREAR',
  RESERVACIONES_EDITAR: 'RESERVACIONES_EDITAR',
  RESERVACIONES_BORRAR: 'RESERVACIONES_BORRAR',
} as const;

export type Permiso = keyof typeof PERMISOS;
